/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syh_tradec_TradeNDKApi */

#ifndef _Included_com_syh_tradec_TradeNDKApi
#define _Included_com_syh_tradec_TradeNDKApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syh_tradec_TradeNDKApi
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_syh_tradec_TradeNDKApi_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
